# start with docker compose up -d
version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_payments
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payments
    ports:
      - "5433:5432"
    volumes:
      - postgres_payments_data:/var/lib/postgresql

volumes:
  postgres_payments_data:
